Resources:
  MicroservicesPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MicroservicesAppPipeline
      RoleArn: arn:aws:iam::<ACCOUNT_ID>:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: <S3_BUCKET_NAME>
      Stages:
        - Name: Source
          Actions:
            - Name: GitSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: microservices-app
                BranchName: main

        - Name: Build
          Actions:
            - Name: DockerBuildAndPush
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: MicroservicesBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployWithHelm
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: MicroservicesDeployProject