version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 883640716669.dkr.ecr.us-east-2.amazonaws.com

      - echo Logging into Docker Hub...
      - DOCKERHUB_CREDS=$(aws secretsmanager get-secret-value --secret-id dockerhub-creds --region us-east-2 --query SecretString --output text)
      - DOCKERHUB_USERNAME=$(echo $DOCKERHUB_CREDS | jq -r .username)
      - DOCKERHUB_PASSWORD=$(echo $DOCKERHUB_CREDS | jq -r .password)
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building images...
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/request-service:latest -f request_service/Dockerfile .
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/ai-processing-service:latest -f ai_processing_service/Dockerfile .
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/response-formatting-service:latest -f response_formatting_service/Dockerfile .
      - docker build --build-arg REACT_APP_REQUEST_SERVICE_URL=$REQUEST_URL --build-arg REACT_APP_FORMATTING_SERVICE_URL=$FORMAT_URL -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/frontend:latest -f frontend/Dockerfile .

      - echo Pushing images...
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/request-service:latest
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/ai-processing-service:latest
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/response-formatting-service:latest
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/frontend:latest

artifacts:
  files:
    - '**/*'