version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 883640716669.dkr.ecr.us-east-2.amazonaws.com

      - echo Logging into Docker Hub...
      - DOCKERHUB_CREDS=$(aws secretsmanager get-secret-value --secret-id dockerhub-creds --region us-east-2 --query SecretString --output text)
      - DOCKERHUB_USERNAME=$(echo $DOCKERHUB_CREDS | jq -r .username)
      - DOCKERHUB_PASSWORD=$(echo $DOCKERHUB_CREDS | jq -r .password)
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo $IMAGE_TAG > image_tag.txt

  build:
    commands:
      - echo Building Docker images with tag $IMAGE_TAG...
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/request-service:$IMAGE_TAG -f request_service/Dockerfile .
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/ai-processing-service:$IMAGE_TAG -f ai_processing_service/Dockerfile .
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/response-formatting-service:$IMAGE_TAG -f response_formatting_service/Dockerfile .
      - docker build -t 883640716669.dkr.ecr.us-east-2.amazonaws.com/frontend:$IMAGE_TAG -f frontend/Dockerfile .

      - echo Pushing Docker images...
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/request-service:$IMAGE_TAG
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/ai-processing-service:$IMAGE_TAG
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/response-formatting-service:$IMAGE_TAG
      - docker push 883640716669.dkr.ecr.us-east-2.amazonaws.com/frontend:$IMAGE_TAG

artifacts:
  files:
    - image_tag.txt

