apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: microservice-sqs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.aiProcessingService.port }}
          env:
            - name: AI_QUEUE_URL
              value: {{ .Values.aiProcessingService.queueUrl }}
            - name: RESPONSE_QUEUE_URL
              value: {{ .Values.responseFormattingService.queueUrl }}